export { default as BlogSection } from './BlogSection';
export { default as ClientsSection } from './ClientsSection';
export { default as CTASection } from './CTASection';
export { default as FAQSection } from './FAQSection';
export { default as FeaturedSection } from './FeaturedSection';
export { HeroSection } from './HeroSection';
export { default as ProcessSection } from './ProcessSection';
export { default as ProjectsSection } from './ProjectsSection';
export { default as ReviewsSection } from './ReviewsSection';
export { default as ServicesSection } from './ServicesSection';
export { default as SliderSection } from './SliderSection';
export { default as WhyChooseUsSection } from './WhyChooseUsSection';
